<?php
use PointStart\ORM\Repository;
use PointStart\Attributes\Query;

abstract class UserRepository extends Repository{
    protected string $entityClass = User::class;

    // ── #[Query] declarations — body generated by make() at runtime ───────────

    #[Query("SELECT * FROM users WHERE name = ? AND email = ?")]
    abstract public function findByNameAndEmailRaw(string $name, string $email): array;

    #[Query("SELECT COUNT(*) FROM users")]
    abstract public function countAll(): int;

    abstract public function findByName(string $name): array;
    // ── Dynamic finders via __call ────────────────────────────────────────────
    //   findByName($name), findByEmail($email)
    //   findOneByEmail($email), existsByEmail($email)
}
?>
